-- 코드를 작성해주세요

SELECT E.ITEM_ID, E.ITEM_NAME, E.RARITY
FROM ITEM_INFO I, ITEM_INFO E, ITEM_TREE T
WHERE I.RARITY = 'RARE' AND I.ITEM_ID = T.PARENT_ITEM_ID AND T.ITEM_ID=E.ITEM_ID
ORDER BY E.ITEM_ID DESC